### PR TITLE
Add global TLS config

### PR DESCRIPTION
**Pull request by ibice**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

Following #574, we'd like to be able to specify a custom CA cert on the Kafka output. This PR adds a way to specify custom CAs as a global (i.e. common to all outputs) TLS option.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

For now, this feature just affects outputs that use the outputs.Client.Post() or Put() methods.

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Hey @ibice 

Thank you for this PR. However, before we look at it, we need you to [sign off your commits](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin). Could you fix that, please? :pray: 

Also, I've noticed some tests are falling, PTAL.

**Comment by ibice** [comment]
Done @leogr, I signed off the commits and solved the linter warnings :)

**Review by Issif — APPROVED** [review]

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Review by leogr — DISMISSED** [review]

**Comment by leogr** [comment]
Hey @ibice 

the CI lint job (which is required) is failing with the following message:
> Error: G402: TLS MinVersion too low. (gosec)

Could you fix it please? :pray: 

cc @Issif

**Comment by ibice** [comment]
@leogr I'll fix it next week, I'm OOO right now

**Comment by Issif** [comment]
I can't review anyway before September, I'm off too

**Comment by ibice** [comment]
@leogr I fixed the linter warning, sorry for the wait

**Review by Issif — APPROVED** [review]

**Pull request merged**
