### PR TITLE
Allow EndsAt field to be specified for alertmanager alerts

### LINKED ISSUE #322: Allow EndsAt field to be specified for alertmanager alerts
**Motivation**
When generating a large number of alerts it would be nice to be able to specify the expiry time, so a different duration can be configured to the global value configured in AM. 

**Feature**
EndsAt field allowed to be configured

**Alternatives**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by danieljmt**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area config
/area outputs

**What this PR does / why we need it**:

Allows the EndsAt alert parameter to be configured

**Which issue(s) this PR fixes**:

Fixes #322

**Special notes for your reviewer**: N/A

### CODE REVIEW

**Review by Issif — CHANGES_REQUESTED** [review]
Seems ok to me, can you update the README please, in both sections, values.yaml and env vars.

**Comment by danieljmt** [comment]
Updated

**Review by Issif — APPROVED** [review]

**Comment by danieljmt** [comment]
Looks like `ci/circleci: lint` has passed but failed to post the status back to GitHub

**Review by fjogeleit — APPROVED** [review]

**Comment by leogr** [comment]
PS
CircleCI was stuck. I have re-run the jobs, hoping they will pass this time :crossed_fingers:

**Pull request merged**
