### PR TITLE
falco helm Chart variables have moved from underscores to CamelCase

### PR DESCRIPTION
**Pull request by czunker**
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>

**What type of PR is this?**

/kind cleanup

/kind documentation

**Any specific area of the project related to this PR?**

/area helm

**What this PR does / why we need it**:

The varibales in the faclo helm Chart have changed, e.g.:
https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L236

Copy&Paste of the example falco config didn't work.

### CODE REVIEW

**Comment by Issif** [comment]
@czunker it's ok for me, you just need to update the chart version and the changelog, it's mandatory for updating in helm hub.

**Comment by czunker** [comment]
@Issif I don't think the helm chart needs an update. The falco helm chart is up-to-date and contains the CamelCase variables. Only the falcosidekick docs need an update to include the new falco variables on how to configure the falco helm chart.

**Review by Issif — APPROVED** [review]

**Comment by Issif** [comment]
@czunker Ok, I approved. Thanks for your help.

**Comment by nibalizer** [comment]
It's a bit confusing. The helm chart uses camelCase and the actual `falco.yaml` that drives the daemon uses underscores. If anything I suppose this is nice that folks copying configs they found on the internet will hopefully just get an error not unintended configuration.

**Pull request merged**
