### PR TITLE
feat: add message thread id in telegramPayload

### PR DESCRIPTION
**Pull request by vashian**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

This enhancement allows for better control over message threading in Telegram.

### CODE REVIEW

**Review by Issif — APPROVED** [review]
This is all good to me, well done

**Comment by Issif** [comment]
Can you sign off your commits please, the CI will decline the merge without.

**Comment by vashian** [comment]
> Can you sign off your commits please, the CI will decline the merge without.

I’ve signed off all my commits as requested.

**Comment by Issif** [comment]
There's still a linting issue:

image

**Review by Issif — APPROVED** [review]
FYI, it will be released with the v2.30.0, I don't have any ETA for now

**Pull request merged**
