### PR TITLE
fix(loki): fix the deadlock in Loki integration

### PR DESCRIPTION
**Pull request by bsod90**
I believe this should be the fix for https://github.com/falcosecurity/falcosidekick/issues/646, but I'm still figuring out a way to test it locally.

### CODE REVIEW

**Review by Issif — APPROVED** [review]
As you confirmed it works, I'm approving.

FYI, I would have used anonymous functions.

Something like:

```go
func (c *Client) LokiPost(falcopayload types.FalcoPayload) {
	c.Stats.Loki.Add(Total, 1)
	c.ContentType = LokiContentType

	if c.Config.Loki.User != "" && c.Config.Loki.APIKey != "" {
		func() {
				c.httpClientLock.Lock()
				defer c.httpClientLock.Unlock()
				c.BasicAuth(c.Config.Loki.User, c.Config.Loki.APIKey)
		}()
	}
```

**Comment by Issif** [comment]
can you sign-off your commit please

**Comment by bsod90** [comment]
Thank you so much, @Issif !
Just added the sign-off
Also, didn't know about anonymous functions, Go isn't my first language :) Thanks!

**Review by Issif — APPROVED** [review]
All good, for the anonymous function I understood so I thought it was interesting to you to mention them :wink:

**Comment by bsod90** [comment]
A quick follow-up question: when do you expect the next minor release to be cut? I'm asking because I'm trying to use Loki integration in our infra and it would be easier to just use the official image instead of forking, custom-building, etc.
Thanks! @Issif

**Comment by Issif** [comment]
@bsod90 I created an RC for you https://github.com/falcosecurity/falcosidekick/releases/tag/2.29.0-rc.3

**Comment by bsod90** [comment]
Thank you!

**Pull request merged**
