### PR TITLE
First crack at a fix to prevent clients from stomping on their headers

### LINKED ISSUE #375: 400 Headers Missing When Firing Multiple Alerts via HTTP Post
**Describe the bug**
When testing the falco/spyderbat integration we were seeing 400's header missing

**How to reproduce it**
setup a simple http service with a nonzero delay and a required header and point the webhook integration at it and fire 2 test events

**Expected behaviour**
200 responses for both request

**Screenshots**
```
2022/10/25 15:51:50 [INFO]  : Webhook - Post OK (200)
2022/10/25 15:51:51 [ERROR] : Webhook - header missing (400): {"message":"Failed to get expected header"}
2022/10/25 15:51:51 [ERROR] : WebHook - header missing
```

**Environment**
Saw first in aws hosted kubernetes, but able to reproduce locally

- Falco version:
```
GitVersion:    2.26.0-36-g76a29e9-dirty
GitCommit:     76a29e9f15dff55c9019d8ba1f9e8dee75c4da50
GitTreeState:  dirty
BuildDate:     '2022-10-21T11:45:18Z'
GoVersion:     go1.19.1
Compiler:      gc
Platform:      linux/amd64
```

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

Kubernetes helm chart and local build from source

**Additional context**

### PR DESCRIPTION
**Pull request by bc-sb**
First crack at a fix to prevent clients from stomping on their own headers

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:
Fixes a race condition that multiple calls to the same http Post causes headers to become unset
**Which issue(s) this PR fixes**:
https://github.com/falcosecurity/falcosidekick/issues/375

Fixes #375 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Issif** [comment]
Thank you for this PR, I'm in holidays this week, I'll take a look asap

**Comment by Issif** [comment]
For all outputs that use the generic `client.Post` method, why are you not locking directly in the method (https://github.com/spyderbat/falcosidekick/blob/d80b603dddd6a2599f6691e48cf21d40f7f2df66/outputs/client.go#L139)? I see you set your `c.m.Lock()` in each output.

**Comment by bc-sb** [comment]
I actually tried that approach originally of just doing a:
```
Lock()
defer Unlock()
```

But was still seeing it...admittedly I got lazy and just crammed it into the clients that were touching the headers to confirm.  But now that I looked at it again, I ran the race detector on it:
```
==================
WARNING: DATA RACE
Write at 0x00c000620110 by goroutine 42:
  github.com/falcosecurity/falcosidekick/outputs.(*Client).Post()
      /home/bc/spyderbat/falcosidekick/outputs/client.go:232 +0x1904
  github.com/falcosecurity/falcosidekick/outputs.(*Client).WebhookPost()
      /home/bc/spyderbat/falcosidekick/outputs/webhook.go:19 +0x1fd
  main.forwardEvent.func22()
      /home/bc/spyderbat/falcosidekick/handlers.go:246 +0xa8                                                                                                                                                                                                                                                                                                                            Previous write at 0x00c000620110 by goroutine 55:
  github.com/falcosecurity/falcosidekick/outputs.(*Client).AddHeader()                                                                                                                            /home/bc/spyderbat/falcosidekick/outputs/client.go:287 +0x7f5
  github.com/falcosecurity/falcosidekick/outputs.(*Client).WebhookPost()
      /home/bc/spyderbat/falcosidekick/outputs/webhook.go:15 +0x6ff                                                                                                                           main.forwardEvent.func22()
      /home/bc/spyderbat/falcosidekick/handlers.go:246 +0xa8  
```

So, I think I have a better option that I will push after seeing that.

**Comment by bc-sb** [comment]
@Issif I just pushed the more robust option.

**Comment by Issif** [comment]
Can you a more explicit name than `m` for the mutex please, I try to keep things explicit for beginners in Go that would like to contribute

**Review by Issif — APPROVED** [review]

**Pull request merged**
