### PR TITLE
Add sns output

### LINKED ISSUE #5: Add event output to a cloud queue
Add in cloud queue as available output.
Example : 
SQS (AWS)
pub/sub (Google)

### PR DESCRIPTION
**Pull request by Issif**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

> /area helm

**What this PR does / why we need it**:

New output `AWS SNS`

**Which issue(s) this PR fixes**:

Fixes #5

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by nibalizer** [comment]
lgtm

**Review by nibalizer — APPROVED** [review]

**Comment by nibalizer** [comment]
Why does @poiana not merge?

**Review by leodido — APPROVED** [review]

**Comment by Issif** [comment]
@poiana is not supposed to merge by itself now?

**Comment by leodido** [comment]
It's blocked by #81 IMHO


Lemme take a look

**Pull request merged**
