### PR TITLE
proposing myself as an approver and a reviewer to the project

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

**What type of PR is this?**

> /kind documentation

**Any specific area of the project related to this PR?**

I'm proposing myself as an approver and a reviewer to the project

### CODE REVIEW

**Comment by Issif** [comment]
I'm OK for my side. For following our procedures, we need to discuss about this in next community call.

**Review by leogr — APPROVED** [review]
:partying_face: 

Welcome :clap:

**Comment by developer-guy** [comment]
> 🥳
> 
> Welcome 👏

Thank you so much, really appreciate it 🥳

**Pull request merged**
