### PR TITLE
remove quotes in label vue for Loki output

### LINKED ISSUE #181: Log pushes for Kubernetes Audit Events to Loki are failing
**Describe the bug**

I'm using falcosidekick to send host os events and Kubernetes audit events to Grafana Loki. If a host os rule is triggered, the event is send to Loki as expected. If I trigger a Kubernetes Audit Event the push to Loki failed with 400 - Header Missing.

Working example for Host Rule:

Bildschirmfoto 2021-02-06 um 20 32 53

The Example described in the Documentation https://falco.org/docs/event-sources/kubernetes-audit/#example failed:

```
2021/02/06 19:26:16 [DEBUG] : Falco's payload : {"output":"20:25:53.706802944: Notice K8s ConfigMap Deleted (user=system:serviceaccount:cattle-system:kontainer-engine configmap=my-config ns=stage resp=200 decision=allow reason=RBAC: allowed by ClusterRoleBinding \"globaladmin-user-r62pf\" of ClusterRole \"cluster-admin\" to User \"user-r62pf\")","priority":"Notice","rule":"K8s ConfigMap Deleted","time":"2021-02-06T19:25:53.706802944Z","output_fields":{"jevt.time":"20:25:53.706802944","ka.auth.decision":"allow","ka.auth.reason":"RBAC: allowed by ClusterRoleBinding \"globaladmin-user-r62pf\" of ClusterRole \"cluster-admin\" to User \"user-r62pf\"","ka.response.code":"200","ka.target.name":"my-config","ka.target.namespace":"stage","ka.user.name":"system:serviceaccount:cattle-system:kontainer-engine","source":"falco"}}
2021/02/06 19:26:16 [DEBUG] : Loki payload : {"streams":[{"labels":"{katargetname=\"my-config\",katargetnamespace=\"stage\",kausername=\"system:serviceaccount:cattle-system:kontainer-engine\",source=\"falco\",jevttime=\"20:25:53.706802944\",kaauthdecision=\"allow\",kaauthreason=\"RBAC: allowed by ClusterRoleBinding \"globaladmin-user-r62pf\" of ClusterRole \"cluster-admin\" to User \"user-r62pf\"\",karesponsecode=\"200\",rule=\"K8s ConfigMap Deleted\",priority=\"Notice\"}","entries":[{"ts":"2021-02-06T19:25:53Z","line":"20:25:53.706802944: Notice K8s ConfigMap Deleted (user=system:serviceaccount:cattle-system:kontainer-engine configmap=my-config ns=stage resp=200 decision=allow reason=RBAC: allowed by ClusterRoleBinding \"globaladmin-user-r62pf\" of ClusterRole \"cluster-admin\" to User \"user-r62pf\")"}]}]}

2021/02/06 19:26:16 [ERROR] : Loki - Header missing (400)
2021/02/06 19:26:16 [ERROR] : Loki - Header missing
```

**How to reproduce it**

1. Installing falco
2. Configure Kube API Server to send Kubernetes Audit Events to falco
3. Install falcosidekick and configure falco http_output send logs
4. Configure falcosidekick to send logs to Loki
5. Try the ConfigMap Example from the Documentation

**Expected behaviour**

Sends Kubernetes Audit Events successfully to Loki

**Screenshots**

See the issue description

**Environment**

- Falco version: 

Falco 0.27.0
Driver version: 5c0b863ddade7a45568c0ac97d037422c9efb750

- System info:

{
  "machine": "x86_64",
  "nodename": "dev-node-3",
  "release": "5.11.0-051100rc6-generic",
  "sysname": "Linux",
  "version": "#202101312230 SMP Sun Jan 31 22:33:58 UTC 2021"
}

- OS: Ubuntu 20.04
- Kernel: Linux 5.11.0-051100rc6-generic
- Installation method: DEB for falco, Helm for falcosidekick

### PR DESCRIPTION
**Pull request by Issif**
Signed-off-by: Issif <issif_github@gadz.org>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

Label values for `Loki` don't support `"`.

**Which issue(s) this PR fixes**:

Fixes #181 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Review by KeisukeYamashita — APPROVED** [review]
LGTM!

**Review by cpanato — DISMISSED** [review]

**Review by leogr — DISMISSED** [review]

**Comment by fntlnz** [comment]
Reopening to let poiana do its thing

**Comment by fntlnz** [comment]
Pod logs for tide say:

```
base branch was modified: Base branch was modified. Review and try the merge again
```

can a maintainer here verify that?

**Comment by leogr** [comment]
Found the issue (see the attached screenshot). 
@Issif a manual rebase should fix it, I will re-approve then. 
Screenshot from 2021-02-08 11-21-01

**Comment by Issif** [comment]
@fntlnz @leogr I did the rebase 👍

**Review by leogr — APPROVED** [review]
I hope this time is the good one :smile_cat:

**Pull request merged**
