### PR TITLE
Refactor project structure to use a pkg.

### PR DESCRIPTION
**Pull request by n3wscott**
/kind cleanup
/kind design

/area config

**What this PR does / why we need it**:

One point of friction with this repo is there is a large amount of code at the root and this code is in the main package, which means it is not importable or vendorable by anything downstream. I am adding a pkg folder as is common in golang projects to make it clear where the common package code is, and pointing the root main function and package to delegate to a new sidekick package.

### CODE REVIEW

**Comment by Issif** [comment]
/hold

Hi @n3wscott, thanks you again.

You’re a little bit too early, this is something I wanted to address for 3.0.0. 
Here my point, I learned a lot with this project, development is not my day job, so I’ve made mistakes for sure BUT some of them was in purpose. My idea was : I’m a beginner, this structure, even if a pro can find it ugly, with a lot of code duplication, is easy to understand for a newGgolang developper which is interested to add a new output. Now, the product is more mature, has a lot of awesome outputs (the most common are there I think), so we can start working of refacto, unit tests, logs, documentation, etc

I'm holding this PR for now, I'll review and we'll discuss about for sure. It's tracked for milestone 3.0.0 of course.

**Comment by n3wscott** [comment]
> You’re a little bit too early, this is something I wanted to address for 3.0.0.

One little thing: this does not change the http api, so no major breaking change, and because the root was not importable before, likely nothing is already using this as a package.

> Here my point, I learned a lot with this project, development is not my day job, so I’ve made mistakes for sure BUT some of them was in purpose. My idea was : I’m a beginner, this structure, even if a pro can find it ugly, with a lot of code duplication, is easy to understand for a newGgolang developper which is interested to add a new output. Now, the product is more mature, has a lot of awesome outputs (the most common are there I think), so we can start working of refacto, unit tests, logs, documentation, etc

No worries at all, I moved a few things around to make it easier to do the next refactor I had in mind. 

> I'm holding this PR for now, I'll review and we'll discuss about for sure. It's tracked for milestone 3.0.0 of course.

I am not sure what that timetable is, but likely it will suck a lot to rebase, so if we are talking more than a little bit of time I will just close this.

We can talk a bit tomorrow at the community meeting. I think there are some misconceptions you might have around how versioning works we can sort out and be more free to make refactorings in-place.

**Comment by leogr** [comment]
A further consideration: to make packages importable by others with go modules, we also will have to prefix the release tags with `v`.

**Comment by n3wscott** [comment]
> A further consideration: to make packages importable by others with go modules, we also will have to prefix the release tags with `v`.

true, you can do it two ways, add a `v2` dir at the root and this sets you up for `v3` or you add a `v2`  to the end of your package in go.mod: https://github.com/falcosecurity/falcosidekick/blob/master/go.mod#L1

Then you need to make a v2 branch to work out of if you move to v3.

**Pull request closed without merging**
