### PR TITLE
AWS Kinesis as an output

### LINKED ISSUE #221: Support AWS Kinesis as an output
**Motivation**

We use AWS kinesis to agregate data and it would be great if the falcosidekick could also natively put to Kinesis. 

**Feature**

Add Kinesis as an AWS output option

**Alternatives**

Today we are writing lambdas to take stuff off SQS and push to kinesis, natively pushing to kinesis would make this a lot simpler and portable.

### PR DESCRIPTION
**Pull request by gauravgahlot**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area outputs

**What this PR does / why we need it**:

This PR adds [AWS Kinesis](https://aws.amazon.com/kinesis/) as an output module.

**Which issue(s) this PR fixes**:

Fixes #221 

**Special notes for your reviewer**:

Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>

### CODE REVIEW

**Comment by Issif** [comment]
@gauravgahlot what's the issue on your side? I left you a comment

**Review by Issif — COMMENTED** [review]
can you update the config_example.yaml file too , please

**Comment by gauravgahlot** [comment]
> @gauravgahlot what's the issue on your side? I left you a comment

I made the changes you suggested. However, I was not able test everything put together, and that's why I didn't request a review again.

**Comment by Issif** [comment]
@gauravgahlot thanks. I reviewed, everything seems OK but I didn't tested it myself either. Tell me when you feel confident enough, I'll approve this PR

**Comment by Issif** [comment]
@gauravgahlot Hello, I know this is a while, but do you think we can merge your PR now?

**Comment by gauravgahlot** [comment]
@Issif Yes, please.

**Review by Issif — APPROVED** [review]

**Pull request merged**
