### PR TITLE
allow to use tls for kafka

### PR DESCRIPTION
**Pull request by Issif**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

/area config

/area outputs

> /area tests

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

#547

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ibice** [comment]
@Issif I was about to PR this same feature! https://github.com/ibice/falcosidekick/commit/7a3aa25fb8b3c0d774048c357f64ba83eee3d2f7

In my solution, I included support for a custom CA. I suppose you plan to support it in the future since you added it to types.go. I'd be happy to add it once this gets merged.

One question out of curiosity, what's the reason behind this? I understand there isn't any client certificate involved.
https://github.com/falcosecurity/falcosidekick/blob/a5ca9ec3575c3107876e4dd0d46790ae4a545584/outputs/kafka.go#L34

**Comment by Issif** [comment]
> @Issif I was about to PR this same feature! [ibice@7a3aa25](https://github.com/ibice/falcosidekick/commit/7a3aa25fb8b3c0d774048c357f64ba83eee3d2f7)
> 
> In my solution, I included support for a custom CA. I suppose you plan to support it in the future since you added it to types.go. I'd be happy to add it once this gets merged.
> 
> One question out of curiosity, what's the reason behind this? I understand there isn't any client certificate involved.
> 
> https://github.com/falcosecurity/falcosidekick/blob/a5ca9ec3575c3107876e4dd0d46790ae4a545584/outputs/kafka.go#L34

I removed the field for the custom ca, I think this config should be global for all outputs, like we do with the key/certs for mTLS. This is something we could add in 2.29.0, don't want to block the 2.28.0 for that.

For the `RequireAndVerifyClientCert` it's useless, I removed it, thanks for the notice.

**Comment by ibice** [comment]
@Issif ok, we can rely on the system CAs for now.

Configuring the CA file globally makes sense. Tell me if you need help, I'll be happy to contribute.

Thanks for the feature!

**Comment by Issif** [comment]
Your contribution is welcome, you can already work on the subject, I'll just add the 2.29.0 as milestone.

**Pull request merged**
