### PR TITLE
docs: Fix typo in README: "ecossytem"

### PR DESCRIPTION
**Pull request by oleg-nenashev**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind documentation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

> /area outputs

> /area tests

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
@oleg-nenashev can you please sign the DCO? :)

**Review by cpanato — DISMISSED** [review]
/lgtm
/approve

**Comment by oleg-nenashev** [comment]
Fixed DCO @cpanato

**Review by Issif — APPROVED** [review]

**Pull request merged**
