### PR TITLE
AWS IRSA support

### LINKED ISSUE #219: AWS Output's don't work with IAM Role Service Accounts.
```falcosidekick-7cd6dc784b-zxbph falcosidekick 	status code: 400, request id: 25768792-8667-4b8c-a281-049320f4ab36

falcosidekick-7cd6dc784b-zxbph falcosidekick 2021/04/07 17:27:05 [INFO]  : AWS CloudWatchLogs - Log Stream not configured creating one called falcosidekick-logstream

falcosidekick-7cd6dc784b-zxbph falcosidekick 2021/04/07 17:27:05 [ERROR] : AWS CloudWatchLogs - AccessDeniedException: User: arn:aws:sts::164382793440:assumed-role/falco-prow-test-infra2021031522165656100000000e/i-0c86c20993deb6679 is not authorized to perform: logs:CreateLogStream on resource: arn:aws:logs:us-west-2:164382793440:log-group:k8s-meetup-falco-alerts:log-stream:falcosidekick-logstream
falcosidekick-7cd6dc784b-zxbph falcosidekick 	status code: 400, request id: f77c160b-9078-452b-9139-b62045e7ecaf
```

**Describe the bug**

FalcoSidekick's AWS Cloudwatch output doesn't work with IRSA (IAM Role Service Accounts). 

**How to reproduce it**
```
1. Install Falcosidekick
helm install falcosidekick \
  --set webui.enabled=true \
  --set webui.image.tag="v1.0.0" \
  --set config.aws.cloudwatchlogs.loggroup="k8s-meetup-falco-alerts" \
  --set config.aws.region="us-west-2" \
  falcosecurity/falcosidekick ```

2. Setup IAM role and OIDC annotation `{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogStreams"
            ],
            "Resource": [
                "arn:aws:logs:*:*:*"
            ]
        }
    ]
}

Assume-role policy.
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::1234567890:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/DDE52ABC393DFEED92ECB2AB8FB56F7B"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.us-west-2.amazonaws.com/id/DDE52ABC393DFEED92ECB2AB8FB56F7B:sub": "system:serviceaccount:prow-monitoring:falcosidekick"
        }
      }
    }
  ]
}

3. Annotate SA `kubectl annotate serviceaccount -n prow-monitoring falcosidekick \
eks.amazonaws.com/role-arn=arn:aws:iam::164382793440:role/falco-prow-test-infra-falcosidekick`

4. Generate event's and see if falcosidekick is able to use IRSA.

```

**Expected behaviour**

It would pull the role credentials from the SA not from the node role.

**Version

Falco sidekick helm chart install.

### PR DESCRIPTION
**Pull request by dchoy**
Use previously created session to avoid using deprecated session.New()
Use session.NewSession() to allow AWS IRSA

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #219 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Issif — APPROVED** [review]
good catch, thank you

**Review by Issif — APPROVED** [review]

**Review by Issif — APPROVED** [review]

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by Issif — APPROVED** [review]

**Pull request merged**
