### PR TITLE
Bug: mTLS client verification fails due to missing ClientCAs configuration in server side

### PR DESCRIPTION
**Pull request by jgmartinez**
**What type of PR is this?**

 /kind bug

**Any specific area of the project related to this PR?**

/area config

**What this PR does / why we need it**:

The PR fixes client mTLS verification from the server when using http_output. 

**Which issue(s) this PR fixes**:

N/A

Fixes #508

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Issif — APPROVED** [review]
Thank you

**Comment by CasperGN** [comment]
Hey @Issif,
Do we need to do something about the lint failing?

**Comment by Issif** [comment]
The logs says a `go fmt` should be run, can you test please

**Comment by jgmartinez** [comment]
Should be good now 😄

**Review by Issif — APPROVED** [review]

**Comment by CasperGN** [comment]
Thanks a bunch for rapid response here!

**Pull request merged**
