### PR TITLE
Update release job

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

- use github actions to run the release job and with that to sign the images/binaries using the keyless mode
- also generate provenance attestations
- drop circleci

next steps: update to use `ko`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cpanato** [comment]
a rehearsal was done here: https://github.com/cpanato/falcosidekick/releases/tag/v99.99.00

**Comment by cpanato** [comment]
test-infra update: https://github.com/falcosecurity/test-infra/pull/1019

**Comment by cpanato** [comment]
@leogr @Issif lets plan a `rc.0` release to test this wdyt?

**Comment by Issif** [comment]
ok for me `2.28.0rc.0`

**Comment by leogr** [comment]
👍

**Pull request merged**
