### PR TITLE
Add and use priority type.

### PR DESCRIPTION
**Pull request by n3wscott**
Signed-off-by: Scott Nichols <snichols@vmware.com>

/kind cleanup

**What this PR does / why we need it**:

I was tripping over the string compares so I made a custom json marshaler and holder for the concept of priority.

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks for this cleanup, much better love it

/lgtm

**Review by KeisukeYamashita — APPROVED** [review]
LGTM, thank you  🚀

**Comment by Issif** [comment]
/lgtm

@cpanato you can unhold for me.

@n3wscott that's elegant and more idiomatic with Go, thank yoy

**Comment by n3wscott** [comment]
apologies, I have some more stuff stacked on this, I am gonna unhold.

/unhold

**Pull request merged**
