### PR TITLE
updated typo in smtp logs.

### PR DESCRIPTION
**Pull request by cartyc**
Found what I think is a small typo in the smtp output. Changed the spelling  from serveur to server.

### CODE REVIEW

**Comment by Issif** [comment]
You're right, Serveur is french word for Server, as you may guess.

I'll merge soon.

Thanks.

**Comment by cartyc** [comment]
Ahh that was my second guess. Is host the same in both Eng/French? If so would it make sense to rename it that.

**Comment by Issif** [comment]
@cartyc `Host` is `Hôte` in French. What occurencies do you want to change?

**Comment by cartyc** [comment]
@Issif I hadn't looked around to find any more but that's something I can do to help make things consistent. I should have asked this before but is having bilingual output something you would be looking for?

**Pull request merged**
