### PR TITLE
Sign release artefacts using cosign

### LINKED ISSUE #300: Sign release artifacts using cosign
**Motivation**

The idea is to sign the release artifacts using [cosign](https://github.com/sigstore/cosign) when doing the release.

This is an initial step for a more secure release and lets the consumers have the ability to verify the release artifacts.

**Feature**

Our project already uses GoReleaser and that makes it easier to implement the signing part.

We need to decide where we will run the release:

- [ ] If we use GitHub Actions we have a feature that we can sign using a keyless approach

- [ ] If we use the correct way using circleci we will need to generate a private/pub certificate and store the password in a circleci context.

**Alternatives**

n/a

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area build

**What this PR does / why we need it**:

 Sign the release artefacts using cosign and also generate the SBOM using syft for now

the secret key is already set in circleci

/assign @leogr @Issif 
cc @danpopnyc 

**Which issue(s) this PR fixes**:

Fixes #300 

**Special notes for your reviewer**:

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
SGTM, but I can't try it.

@Issif @cpanato do we want to merge it directly and see what happens?

**Comment by cpanato** [comment]
@leogr I've run in a sample repo the commands and that worked :)

let's try, what we can do is when we cut the release, I will be watching to check and if fail can act right away

@Issif

**Comment by Issif** [comment]
I think I will work on the new release this month, I would to manage `source` and `tags` in payload first, this is important because of plugins and talon, but this is a big work as we have many outputs

**Comment by Issif** [comment]
@cpanato I created the PR for dealing with source and tags in the events, feel free to rebase this PR on it after

**Comment by leogr** [comment]
> @cpanato I created the PR for dealing with source and tags in the events, feel free to rebase this PR on it after

There are no conflicts. I guess we can approve this PR. @Issif is that ok for you?

**Comment by cpanato** [comment]
i can rebase just to make sure, one sec

**Comment by cpanato** [comment]
@leogr @Issif rebased

**Review by Issif — APPROVED** [review]
:heart:

**Comment by cpanato** [comment]
@Issif when you cut let me know in case we need to tweak anything :)

**Pull request merged**
