### PR TITLE
resolve gosec issues or add nosec annotations

### PR DESCRIPTION
**Pull request by alsm**
Signed-off-by: Al Stockdill-Mander <asm@uk.ibm.com>

/kind cleanup

**What this PR does / why we need it**:

Our build process requires no gosec issues, I have resolved them by appropriate remediation or added nosec annotations with justification.

Also fixed a couple of things the linter was complaining about.

### CODE REVIEW

**Comment by Issif** [comment]
/lgtm

Thank you, it's a really valuable PR.

Even if all is OK for me, I don't want to merge it right now. From my point of view, if we're trying to respect `gosec` it's something we need to add in Makefile and CircleCI for avoiding later issues.

WDYT @cpanato @KeisukeYamashita @leogr ?

**Review by cpanato — APPROVED** [review]
/lgtm

in the future we might want to return an error here: https://github.com/falcosecurity/falcosidekick/pull/179/files#diff-0e426a43248661127a0c0ee115aef7a1093b635f8993b3f7ebb1dd9f05b8f249R162 and not just log

**Comment by cpanato** [comment]
/hold cancel

thanks for your PR

**Pull request merged**
